# Generated by Django 5.1.2 on 2025-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('toAddress', models.TextField()),
                ('mesh_30', models.IntegerField()),
                ('mesh_40', models.IntegerField()),
                ('mesh_60', models.IntegerField()),
                ('mesh_80', models.IntegerField()),
                ('mesh_150', models.IntegerField()),
                ('mesh_30_40', models.IntegerField()),
                ('mesh_40_60', models.IntegerField()),
                ('mesh_60_80', models.IntegerField()),
                ('mesh_80_100', models.IntegerField()),
            ],
        ),
    ]
