# Generated by Django 5.1.2 on 2025-01-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('toName', models.CharField(max_length=150)),
                ('gstin', models.CharField(max_length=15)),
                ('invoiceDate', models.DateField()),
                ('shippingAddress', models.CharField(max_length=90)),
                ('bankName', models.CharField(max_length=15)),
                ('accNo', models.CharField(max_length=12)),
                ('ifscCode', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('gstIN', models.CharField(max_length=20)),
                ('toAddress', models.TextField()),
                ('mesh_30', models.IntegerField()),
                ('mesh_40', models.IntegerField()),
                ('mesh_60', models.IntegerField()),
                ('mesh_80', models.IntegerField()),
                ('mesh_150', models.IntegerField()),
                ('mesh_30_40', models.IntegerField()),
                ('mesh_40_60', models.IntegerField()),
                ('mesh_60_80', models.IntegerField()),
                ('mesh_80_100', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=50)),
                ('hsn', models.CharField(max_length=45)),
                ('qty', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('amt', models.CharField(max_length=50)),
                ('grandTotal', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.bill')),
            ],
        ),
    ]
