# Generated by Django 5.1.2 on 2025-01-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gstIN',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
