# Generated by Django 5.1.2 on 2025-01-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='eWayBill',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
