# Generated by Django 5.1.2 on 2025-01-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0002_company_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invNo', models.IntegerField(auto_created=True)),
                ('toName', models.CharField(max_length=150)),
                ('gstin', models.CharField(max_length=15)),
                ('invoiceDate', models.DateTimeField()),
                ('eWayBill', models.CharField(max_length=15)),
                ('shippingAddress', models.CharField(max_length=50)),
                ('items', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('bankName', models.CharField(max_length=15)),
                ('accNo', models.CharField(max_length=12)),
                ('ifscCode', models.CharField(max_length=12)),
            ],
        ),
    ]
