# Generated by Django 5.1.2 on 2025-01-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0003_rename_shippingaddress_bill_shippingadd_bill_toadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='shippingAdd',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='toAdd',
            field=models.CharField(max_length=150),
        ),
    ]
