# Generated by Django 5.1.2 on 2025-01-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_alter_bill_shippingadd_alter_bill_toadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='gstin',
            field=models.CharField(max_length=25),
        ),
    ]
