# Generated by Django 5.1.2 on 2025-01-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_remove_bill_amount_remove_bill_ewaybill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
