# Generated by Django 5.1.2 on 2025-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0005_company_bno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bno',
        ),
        migrations.AddField(
            model_name='bill',
            name='bno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='invoiceDate',
            field=models.DateField(),
        ),
    ]
