# Generated by Django 5.1.2 on 2025-01-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0006_remove_company_bno_bill_bno_alter_bill_invoicedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product1', models.CharField(max_length=15)),
                ('hsn', models.CharField(max_length=10)),
                ('qty1', models.IntegerField()),
                ('rate1', models.IntegerField()),
                ('amt1', models.IntegerField()),
                ('hsn2', models.CharField(max_length=10)),
                ('qty2', models.IntegerField()),
                ('rate2', models.IntegerField()),
                ('amt2', models.IntegerField()),
                ('product2', models.CharField(max_length=15)),
                ('hsn3', models.CharField(max_length=10)),
                ('qty3', models.IntegerField()),
                ('rate3', models.IntegerField()),
                ('am31', models.IntegerField()),
                ('product4', models.CharField(max_length=15)),
                ('hsn4', models.CharField(max_length=10)),
                ('qty4', models.IntegerField()),
                ('rate4', models.IntegerField()),
                ('amt4', models.IntegerField()),
                ('grandTotal', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.products'),
        ),
    ]
