# Generated by Django 5.1.2 on 2025-01-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0007_products_alter_bill_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='hsn',
            new_name='hsn1',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product1',
            new_name='items',
        ),
    ]
