# Generated by Django 5.1.2 on 2025-01-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0008_rename_hsn_products_hsn1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='am31',
            new_name='amt',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='hsn1',
            new_name='hsn',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='amt1',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='amt2',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='products',
            name='amt4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='hsn2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='hsn3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='hsn4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='qty2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='qty3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='qty4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rate1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rate2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rate3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rate4',
        ),
    ]
