# Generated by Django 5.1.2 on 2025-01-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0009_rename_am31_products_amt_rename_hsn1_products_hsn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='items',
            new_name='product',
        ),
    ]
