# Generated by Django 5.1.2 on 2025-01-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0010_rename_items_bill_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bill.bill'),
            preserve_default=False,
        ),
    ]
