# Generated by Django 5.1.2 on 2025-01-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0011_remove_bill_product_products_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='bill',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.products'),
        ),
    ]
