# Generated by Django 5.1.2 on 2025-01-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0012_remove_products_bill_alter_bill_bno'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bill.bill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='bno',
            field=models.IntegerField(),
        ),
    ]
