# Generated by Django 5.1.2 on 2025-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0013_products_bill_alter_bill_bno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='amt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='hsn',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='products',
            name='items',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='qty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='rate',
            field=models.CharField(max_length=50),
        ),
    ]
