# Generated by Django 5.1.2 on 2025-01-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0014_alter_products_amt_alter_products_hsn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='shippingAddress',
            field=models.CharField(max_length=90),
        ),
    ]
